[project]
name = "py-hashchecker"
version = "0.1.0"
description = "Python Frontend to RAHashChecker"
readme = "README.md"
authors = [
    { name = "Faleh Alotaibi", email = "121350271+f-alotaibi@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "api-python",
]

[tool.uv.sources]
api-python = { git = "https://github.com/RetroAchievements/api-python", rev = "f6ef9be95d400927e9bda774538053d5ec7080cf" }
